### ISSUE TITLE
Unable to Run Adobe DNG Converter from Python

### ISSUE THREAD

**Issue by JoeWise** [colour-science/colour-hdri#23]
I've been trying to run the [Merge from Raw Files with Post Demosaicing](https://github.com/colour-science/colour-hdri/blob/master/colour_hdri/examples/examples_merge_from_raw_files_with_post_demosaicing.ipynb) example and I'm running into an issue where Adobe DNG Converter does not run when it's called. The code progresses without any errors, but the .dng files are not created. 

I'm on Windows. I've installed Adobe DNG Converter and added the executable to my Path. I'm able to run the exact same command colour-hdri is trying to run in convert_raw_files_to_dng_files() from the command line without issue ("Adobe DNG Converter" -e -d "C:\path\to\images" "C:\path\to\images\IMG.CR2"). I've tried running from an admin console, but still get the same issue. 

I realize this isn't strictly a colour-hdri issue, but figured others might have come across this issue as well.

**Comment by JoeWise** [comment]
I figured out that the example changes the `DNG_CONVERSION_ARGUMENTS` without accounting for if the platform is Windows or not, so it adds extra double quotations that make Adobe DNG Converter not recognize the path.

To fix this I changed line 140 from the example:
`colour_hdri.process.dng.DNG_CONVERSION_ARGUMENTS = '-e -d "{0}" "{1}"'`
to 
`colour_hdri.process.dng.DNG_CONVERSION_ARGUMENTS = '-e -d {0} {1}`

**Comment by KelSolaar** [comment]
Sorry for the late reply @JoeWise and thanks!
