### ISSUE TITLE
Error when using absolute_luminance_calibration_Lagarde2016()

### ISSUE THREAD

**Issue by ahemberger** [colour-science/colour-hdri#36]
### Question

Hiyo again;

I have a bit of code that does this:

```
        (img, attribs) = colour.read_image(os.path.abspath(file), 
                                method="OpenImageIO", 
                                attributes=True )

        img = colour_hdri.absolute_luminance_calibration_Lagarde2016(img, LUX) # lux is an input arg
```
Trying to run it, I see:

`numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('float64'), dtype('<U5')) -> None`

Is there a data type conversion I should be doing when passing the image to this function?

**Comment by KelSolaar** [comment]
Hi @ahemberger,

Seems like "LUX" is a Unicode string here, try to cast it to float and this will work!

Cheers,

Thomas
